<a href="https://colab.research.google.com/github/LekhanaGN/GridSearch_CV/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x=df.drop('species',axis=1)

In [8]:
y=df['species']

In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
model_knn=KNeighborsClassifier(n_neighbors=13)

In [18]:
model_knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=13)

In [19]:
model_knn.score(X_test,Y_test)

1.0

In [30]:
from sklearn.svm import SVC


model_svm = SVC(gamma= 'auto')


model_svm.fit(X_train,Y_train)

SVC(gamma='auto')

In [31]:
model_svm.score(X_test,Y_test)

1.0

# now lets use grid search CV

In [32]:
from sklearn.model_selection import GridSearchCV

In [34]:
classifier=GridSearchCV((model_svm),{
    'C':[1,10,20,30]
    ,'kernel':['rbf','linear'],
},cv=5,return_train_score=False)

In [37]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [39]:
classifier.cv_results_

{'mean_fit_time': array([0.00551276, 0.00693073, 0.01051798, 0.0087008 , 0.00424137,
        0.00367279, 0.00376406, 0.005516  ]),
 'std_fit_time': array([0.00126268, 0.00276683, 0.00093811, 0.00258111, 0.00028785,
        0.00010662, 0.00010418, 0.00214211]),
 'mean_score_time': array([0.00368552, 0.0060833 , 0.00818491, 0.0064961 , 0.00320196,
        0.0026854 , 0.00286193, 0.00493517]),
 'std_score_time': array([5.40530147e-04, 2.22982268e-03, 6.96489253e-04, 1.89750073e-03,
        3.09527043e-04, 8.01192288e-05, 7.88071182e-05, 2.03321645e-03]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [40]:
results=pd.DataFrame(classifier.cv_results_)

In [41]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005513,0.001263,0.003686,0.000541,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.006931,0.002767,0.006083,0.002230,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.010518,0.000938,0.008185,0.000696,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.008701,0.002581,0.006496,0.001898,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.004241,0.000288,0.003202,0.000310,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003673,0.000107,0.002685,0.000080,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003764,0.000104,0.002862,0.000079,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.005516,0.002142,0.004935,0.002033,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [42]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [47]:
param_grid = {
    'n_neighbors': np.arange(1, 31),             # Test K values from 1 to 30
    'weights': ['uniform', 'distance'],          # Strategy used to weight data points
    'metric': ['euclidean', 'manhattan', 'minkowski'] # Distance metrics
}

In [49]:
classifier2=GridSearchCV(
    estimator=model_knn,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

In [50]:
classifier2.fit(x,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [51]:
classifier.cv_results_

{'mean_fit_time': array([0.00551276, 0.00693073, 0.01051798, 0.0087008 , 0.00424137,
        0.00367279, 0.00376406, 0.005516  ]),
 'std_fit_time': array([0.00126268, 0.00276683, 0.00093811, 0.00258111, 0.00028785,
        0.00010662, 0.00010418, 0.00214211]),
 'mean_score_time': array([0.00368552, 0.0060833 , 0.00818491, 0.0064961 , 0.00320196,
        0.0026854 , 0.00286193, 0.00493517]),
 'std_score_time': array([5.40530147e-04, 2.22982268e-03, 6.96489253e-04, 1.89750073e-03,
        3.09527043e-04, 8.01192288e-05, 7.88071182e-05, 2.03321645e-03]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [52]:
results=pd.DataFrame(classifier.cv_results_)

In [53]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [54]:
from sklearn.model_selection import RandomizedSearchCV

In [57]:
classifier_r=RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30]
    ,'kernel':['rbf','linear'],
},n_iter=4,cv=5,return_train_score=False)

In [58]:
classifier_r.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [60]:
classifier_r.cv_results_

{'mean_fit_time': array([0.01001105, 0.00432177, 0.00415449, 0.00383143]),
 'std_fit_time': array([3.84121988e-03, 2.40517646e-04, 5.12721690e-05, 2.87857884e-04]),
 'mean_score_time': array([0.00668082, 0.00324006, 0.00299549, 0.00279112]),
 'std_score_time': array([3.48838602e-03, 2.79050279e-04, 5.80240487e-05, 1.54515209e-04]),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[10, 20, 30, 1],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'rbf', 'C': 10},
  {'kernel': 'linear', 'C': 20},
  {'kernel': 'rbf', 'C': 30},
  {'kernel': 'linear', 'C': 1}],
 'split0_test_score': array([0.96666667, 1.        , 0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.9       , 0.9       , 0.96666667]),
 'split3_test_score': array([0.96666667, 0.93333333, 0.93333333, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.96666667, 0.96      , 0.98      ]),
 'std_test_score': array([0.01632993, 0.0421637 , 0.03887301, 0.01632993]),
 'rank_test_score': array([1, 3, 4, 1], dtype=int32)}

In [61]:
results=pd.DataFrame(classifier_r.cv_results_)

In [62]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       20       linear         0.966667
2       30          rbf         0.960000
3        1       linear         0.980000